### ISSUE TITLE
Apply a Gaussian filter to satellite image at a specified scale.

### ISSUE THREAD

**Issue by nikosGeography** [ethanplunkett/gridkernel#1]
I have the PAN band from Landsat 8 (15m resolution) and I would like to apply a Gaussian filter to the image at 460m. The reason is that I want to measure the effect of the point spread function (PSF) while downscaling a satellite image. The PAN band assists the downscaling process as it is used as a covariate.

The function `gaussiansmooth` requires to set the parameters `max.r`, `kernel.dim` and `max.p.na` which I am not sure what values should I use. For the `sd` parameter I will start from 0.2 all the way up to 0.9 with step 0.05 (note that the image pixel size is in meters).

From the paper _The effect of point spread function on downscaling continua_  the authors investigated various PSF parameters ranging from 0.2 to 0.9 (I am referring to the sigma value of a Gaussian filter).
Could you please assist me on what values should I set for those parameters?
Here is the dataset:
```
new("RasterLayer", file = new(".RasterFile", name = "C:\\Users\\Geography\\Desktop\\a\\pan.tif", 
    datanotation = "FLT4S", byteorder = "little", nodatavalue = -Inf, 
    NAchanged = FALSE, nbands = 1L, bandorder = "BIL", offset = 0L, 
    toptobottom = TRUE, blockrows = 256L, blockcols = 256L, driver = "gdal", 
    open = FALSE), data = new(".SingleLayerData", values = logical(0), 
    offset = 0, gain = 1, inmemory = FALSE, fromdisk = TRUE, 
    isfactor = FALSE, attributes = list(), haveminmax = FALSE, 
    min = Inf, max = -Inf, band = 1L, unit = "", names = "pan"), 
    legend = new(".RasterLegend", type = character(0), values = logical(0), 
        color = logical(0), names = logical(0), colortable = logical(0)), 
    title = character(0), extent = new("Extent", xmin = 582700, 
        xmax = 604300, ymin = 1005700, ymax = 1047400), rotated = FALSE, 
    rotation = new(".Rotation", geotrans = numeric(0), transfun = function () 
    NULL), ncols = 216L, nrows = 417L, crs = new("CRS", projargs = "+proj=lcc +lat_0=18.88015774 +lon_0=76.75 +lat_1=16.625 +lat_2=21.125 +x_0=1000000 +y_0=1000000 +datum=WGS84 +units=m +no_defs"), 
    history = list(), z = list())
```

**Comment by ethanplunkett** [comment]
Hi Nikos, 

Your sd parameters of 0.5 to .9 meters seems very low to me as they are much less than your cellsize of 15 meters  Is that what you want?  If so then the default max.r  of 3 times the SD isn't going to work for you as it is still less than a cell so your kernel ends up with a single cell.  You could try setting your max.r to 15 meters which would force it to be 3 x 3 cells. However, almost all the weight will be on the focal cell so the output will be almost identical to the input. The makegaussiankernel function is used to create the kernel of weights that is in turn used to calculate the moving window average for each focal cell so we can use it to examine the weights with your parameters (with modified max.r):

`makegaussiankernel(sd = 1, cellsize = 15, max.r = 15)`
produces:
[1,] 0.000000e+00 1.386343e-49 0.000000e+00
[2,] 1.386343e-49 1.000000e+00 1.386343e-49
[3,] 0.000000e+00 1.386343e-49 0.000000e+00

Is it possible that the 0.5 to 0.9 you are considering were expressed in cells not meters?  That would make a lot more sense.  Here's a kernel with an sd of 0.9 cells  (13.5 m):
`makegaussiankernel(sd = 0.9  * 15, cellsize = 15)`
produces:
[1,] 0.000000000 0.009086824 0.01684594 0.009086824 0.000000000
[2,] 0.009086824 0.057897681 0.10733570 0.057897681 0.009086824
[3,] 0.016845936 0.107335698 0.19898814 0.107335698 0.016845936
[4,] 0.009086824 0.057897681 0.10733570 0.057897681 0.009086824
[5,] 0.000000000 0.009086824 0.01684594 0.009086824 0.000000000

Those parameters used with gaussiansmooth would smooth the image with most of the weight on the center cell and it's immediate neighbors. 

Best,
Ethan

**Comment by nikosGeography** [comment]
_Is it possible that the 0.5 to 0.9 you are considering were expressed in cells not meters?_
I quote from the paper I mentioned, p.254: _Gaussian PSF (width is 0.5 coarse pixel size)_ From this I understand that the authors are referring to meters, but again I might be wrong. 

To put it differently, I'm trying to simulate coarse data (i.e., the PAN band at 460m) as though it was measured with a coarse PSF. To do this I need to apply a transfer function (TF; e.g., Gaussian) to the fine data, but with a **very large width**. This produces the coarse data. I am guessing that I need to apply PSF (the Gaussian filter, because I am assuming that the PSF is Gaussian) with an appropriate (large) sigma. 

My initial question is what should the sigma value be in order to simulate the coarse resolution PAN band.

I hope I stated my problem clear enough.

**Comment by ethanplunkett** [comment]
I would read "0.5 coarse pixel size" to be  0.5 * 450 m or 225m  The function will work fine with that.

**Comment by nikosGeography** [comment]
That's a progress! So if I understand correctly, firstly I need to use the function `makegaussiankernel` and then run the `gaussiansmooth`. Am I right?

**Comment by ethanplunkett** [comment]
Just use gaussiansmooth it will call makegaussiankernel.

**Comment by nikosGeography** [comment]
Okay, I will run it and I'll update the post with the results.

**Comment by nikosGeography** [comment]
Hi Ethan, I am trying to run the function `gaussiansmooth` but I am constantly receiving an error: `Error in UseMethod("gaussiansmooth") : no applicable method for 'gaussiansmooth' applied to an object of class "c('RasterLayer', 'Raster', 'BasicRaster')"`. This is when I use my original raster.
When I convert it into a `matrix` I am getting this error: `Error in UseMethod("gaussiansmooth") : no applicable method for 'gaussiansmooth' applied to an object of class "c('matrix', 'array', 'double', 'numeric')"`.

Here is my code:
```
library(gridkernel)
library(gridprocess)

pan = raster("path/pan15.tif")

m = as.matrix(pan) # when I convert it into a matrix

smoothed = gaussiansmooth(m,
                          sd = 0.5 * 920) # I set 0.5*920 because I want my output raster to have 460m pixel size
```

Why that error?

**Comment by ethanplunkett** [comment]
Try:
```
pan = raster("path/pan15.tif")
g <- as.grid(pan)
smoothed = gaussiansmooth(g, sd = 0.5 * 920)
r <- raster(smoothed)
```

**Comment by nikosGeography** [comment]
I tried your code and many more other variations. The good thing is that by using the `as.grid` function I managed some progress. The issue is that it does blur the image but it does **not** upscale it to 460m. If I interpret correctly the documentation the `kernel.dim` is responsible for the amount of upscaling. No matter what value I insert to the `kernel.dim` parameter inside the `gaussiansmooth` the resolution of the raster (i.e., the pixel size) remains the same as my original (15m).

Here is one of my attempts:

```
pan = raster("path/pan15.tif")

g <- as.grid(pan)

smoothed = gaussiansmooth(g, 
                          sd = 0.5 * 460,
                          kerdel.dim = 63)

r <- raster(smoothed)

plot(r)
res(r)
```
In fact, the `kernel.dim` it seems that it has no impact on the upscaling. Maybe I am doing something wrong here. Any recommendations?

**Comment by ethanplunkett** [comment]
The gaussiansmooth function always returns the same extent and cellsize as the input grid.  Internally it uses upscaling to reduce processing time and the kerneldim parameter is used to control the amount of upscaling - to fine tuning the trade off between precision and speed.  

So, if you want a different resolution you'll have to upscale the result separately.  If you are happy with a new cellsize that is an integer multiple of the original cellsize you could use upscale() but it wasn't intended for general usage and so may not be the best way to do that.   See [https://stackoverflow.com/questions/32278825/how-to-change-the-resolution-of-a-raster-layer-in-r](url) for other options.

**Comment by nikosGeography** [comment]
Yes you are right, its written in the documentation. Okay, I think we can close the issue now. It's not what I am looking for but I appreciate your help so far.
